{% set data = load_setup_py_data() %}

package:
  name: covid-if-annotations
  version: 0.0.3dev1

source:
  path: ..

build:
  number: 0
  skip: True  # [py<36]
  entry_points:
    {% for ep in data['entry_points']['console_scripts'] %}
    - {{ ep }}
    {% endfor %}
requirements:
  build:
    - python
    - pip
  run:
    - python
    # dependencies are defined in setup.py
    {% for dep in data['install_requires'] %}
    - {{ dep.lower() }}
    {% endfor %}


about:
  home: https://github.com/hci-unihd/covid-if-annotations
  author: Constantin Pape
  license: MIT
