{% set data = load_setup_py_data() %}

package:
  name: covid-if-annotations
  version: 0.0.0dev2

source:
  path: ..

build:
  noarch: python
  script:
        - python -m pip install --no-deps --ignore-installed .
  entry_points:
    {% for ep in data['entry_points']['console_scripts'] %}
    - {{ ep }}
    {% endfor %}
requirements:
  build:
    - python >=3.6
    - pip
    - setuptools-scm
  run:
    - python >=3.6
    # dependencies are defined in setup.py
    {% for dep in data['install_requires'] %}
    - {{ dep.lower() }}
    {% endfor %}


about:
  home: https://github.com/hci-unihd/covid-if-annotations
  author: Constantin Pape
  license: MIT
